"ui.background" = { bg = "white", fg = "black" }
"ui.selection" = { bg = "black", fg = "white" }
"ui.background.separator" = "gray"
"ui.linenr" = "gray"
"ui.linenr.selected" = { bg = "black", fg = "white" }
"ui.statusline" = { bg = "black", fg = "white" }
"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { bg = "light-gray", fg = "black" }
"ui.popup" = { fg = "white", bg = "black" }
"ui.help" = { fg = "white", bg = "black" }

"string" = { bg = "light-green", fg = "black" }
"constant" = { bg = "light-cyan", fg = "black" }
"comment" = { bg = "light-magenta", fg = "black" }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "gray"

"warning" = { fg = "black", bg = "light-yellow" }
"error" = { fg = "black", bg = "light-red" }
"hint" = { fg = "black", bg = "light-blue" }

"diagnostic.warning" = { fg = "black", bg = "light-yellow" }
"diagnostic.error" = { fg = "black", bg = "light-red" }
"diagnostic.hint" = { fg = "black", bg = "light-blue" }
