# Author : Tomas Ruud <git@me.2ms.no>

"ui.selection" = { fg = "white", bg = "gray" }
"ui.cursor" = { fg = "black", bg = "light-gray" }
"ui.cursor.primary" = { fg = "black", bg = "light-gray" }
"ui.cursor.match" = { underline = { style = "line" } }
"ui.background.separator" = "gray"
"ui.linenr" = "gray"
"ui.linenr.selected" = { fg = "white", bg = "gray" }
"ui.statusline" = { bg = "black", fg = "white" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.virtual.ruler" = { underline = { style = "line" } }
"ui.virtual.jump-label" = { underline = { style = "line" } }

"string" = { fg = "green" }
"constant" = { fg = "cyan" }
"comment" = { fg = "magenta" }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "gray"

"warning" = "yellow"
"error" = "red"
"hint" = "gray"

"diagnostic" = { underline = { style = "line" } }
